-- All tables has
-- id: primary_key, int, for join requests and foreign keys, should not be exposed to service clients
-- uri: unique identifier, immutable, can be exposed
-- creation_datetime: for diagnostics


CREATE TABLE recall_db_schema.user(
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   uri TEXT NOT NULL UNIQUE,
   firebase_auth_uid TEXT NOT NULL UNIQUE, -- for connection
   email TEXT NOT NULL UNIQUE,
   creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE recall_db_schema.workspace(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uri TEXT NOT NULL UNIQUE,
    creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE recall_db_schema.workspace_member(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES recall_db_schema.workspace(id),
    user_id BIGINT NOT NULL REFERENCES recall_db_schema.user(id),
    creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE(workspace_id, user_id)
);


CREATE TABLE recall_db_schema.item(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uri TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL UNIQUE,
  text_content TEXT NOT NULL UNIQUE,
  last_modification_datetime TIMESTAMPTZ NOT NULL,
  workspace_id BIGINT NOT NULL REFERENCES recall_db_schema.workspace(id),
  creator_id BIGINT NOT NULL REFERENCES recall_db_schema.workspace_member(id),
  creation_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);


