// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf1Y2BhFCEzGMGJr60VAhLGXFjsYdnQ4o',
    appId: '1:540476119365:web:e24c369160868b0c5f062c',
    messagingSenderId: '540476119365',
    projectId: 'recall-f4094',
    authDomain: 'recall-f4094.firebaseapp.com',
    storageBucket: 'recall-f4094.appspot.com',
    measurementId: 'G-LMT19ZMNS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKS0GhAbKia225Ojmn6NOSIgW2gNGlKxc',
    appId: '1:540476119365:android:1e9bf482b405fdf45f062c',
    messagingSenderId: '540476119365',
    projectId: 'recall-f4094',
    storageBucket: 'recall-f4094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3w8FQpKms4k1m1HY0Mn2EzPgtimVmxIw',
    appId: '1:540476119365:ios:35765a7be069dad55f062c',
    messagingSenderId: '540476119365',
    projectId: 'recall-f4094',
    storageBucket: 'recall-f4094.appspot.com',
    iosClientId: '540476119365-c0a05qj7prnis0ubqv4ruvlp6mfm7t9l.apps.googleusercontent.com',
    iosBundleId: 'com.recall.recallApp',
  );
}
